--------------------------------------------------------
--  파일이 생성됨 - 일요일-6월-28-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "JSP"."CART" 
   (	"ID" NUMBER(10,0), 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"BRAND" VARCHAR2(50 BYTE), 
	"PRICE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JSP_TABLESPACE" ;
REM INSERTING into JSP.CART
SET DEFINE OFF;
Insert into JSP.CART (ID,CATEGORY,NAME,BRAND,PRICE) values (1,'사료','뉴트리나 건강백서 슈나우져 2kg','카길애그리퓨리나',4500);
Insert into JSP.CART (ID,CATEGORY,NAME,BRAND,PRICE) values (2,'사료','쿠쿳 강아지 어덜트 피쉬 1.5kg','쿠쿳펫푸드',5550);
Insert into JSP.CART (ID,CATEGORY,NAME,BRAND,PRICE) values (3,'사료','뉴트리나 2kg 강아지사료','카길애그리퓨리나',9000);
Insert into JSP.CART (ID,CATEGORY,NAME,BRAND,PRICE) values (4,'사료','더리얼 닭고기 어덜트 1Kg','하림펫푸드',100000);
--------------------------------------------------------
--  DDL for Index CART_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JSP"."CART_PK" ON "JSP"."CART" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JSP_TABLESPACE" ;
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "JSP"."CART" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "JSP"."CART" ADD CONSTRAINT "CART_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JSP_TABLESPACE"  ENABLE;
