--------------------------------------------------------
--  파일이 생성됨 - 일요일-6월-28-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PHOTO
--------------------------------------------------------

  CREATE TABLE "JSP"."PHOTO" 
   (	"ID" NUMBER(10,0), 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"CONTENT" VARCHAR2(100 BYTE), 
	"IMAGE" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JSP_TABLESPACE" 
 LOB ("IMAGE") STORE AS SECUREFILE (
  TABLESPACE "JSP_TABLESPACE" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into JSP.PHOTO
SET DEFINE OFF;
Insert into JSP.PHOTO (ID,CATEGORY,NAME,CONTENT) values (1,'개','골댕이','금빛의 풍성한 털이 가장 큰 특징이며 은은하게 귀티가 흐르는 인상이다.');
Insert into JSP.PHOTO (ID,CATEGORY,NAME,CONTENT) values (2,'개','그레이하운드','가장 큰 특징이라면 역시 속도. 개 중에서 가장 빨리 달리는 개이다');
Insert into JSP.PHOTO (ID,CATEGORY,NAME,CONTENT) values (3,'개','닥스훈트','원통을 연상시키는 비정상적으로 긴 허리와 짧은 다리로 유명하다');
Insert into JSP.PHOTO (ID,CATEGORY,NAME,CONTENT) values (4,'개','사모예드','개다');
--------------------------------------------------------
--  DDL for Index PHOTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JSP"."PHOTO_PK" ON "JSP"."PHOTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JSP_TABLESPACE" ;
--------------------------------------------------------
--  Constraints for Table PHOTO
--------------------------------------------------------

  ALTER TABLE "JSP"."PHOTO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "JSP"."PHOTO" ADD CONSTRAINT "PHOTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JSP_TABLESPACE"  ENABLE;
